<a href="https://colab.research.google.com/github/philsaurabh/Pytorch-zero-to-GANs-Jovian/blob/main/Pytorch_Zero_to_GANs_Py_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Importing libraries

In [1]:
import torch
import numpy as np

# Tensor
It is generalization term for vector, matrix or any n-dimensional array. It's an umbrella term.

### To create a floating point number in python (and pytorch) we use shorthand of that number.

In [2]:
number1=torch.tensor(1.)
number2=torch.tensor(2.1)
print(number1)
print(number2)
print(number1.dtype)
print(number1.shape)
print(number2.dtype)

tensor(1.)
tensor(2.1000)
torch.float32
torch.Size([])
torch.float32


### To create vector

In [3]:
vector1=torch.tensor([1,2,3.,4,5])
print(vector1)
print(vector1.shape)
print(vector1.dtype)

tensor([1., 2., 3., 4., 5.])
torch.Size([5])
torch.float32


All converted to floating point number

### To create matrix

In [4]:
matrix1=torch.tensor([[1.,2],[2.,3],[4,5],[7,9]])
print(matrix1)
print(matrix1.shape)
print(matrix1.dtype)

tensor([[1., 2.],
        [2., 3.],
        [4., 5.],
        [7., 9.]])
torch.Size([4, 2])
torch.float32


4 rows 2 columns

### n-dimensional array

In [5]:
arr1=torch.tensor([[[1,2],[2,3]],[[4,5],[7,9]]])
arr2=torch.tensor([[[1.,2],[2,3]],[[4,5],[7,9]]])
print(arr1)
print(arr1.shape)
print(arr1.dtype)
print(arr2)
print(arr2.shape)
print(arr2.dtype)
try:
  arr3=torch.tensor([[[1.,2,.2],[2,3]],[[4,5],[7,9]]])
  print(arr3.shape)
  print(arr3.dtype)
except ValueError as err:
  print(err)
  print(ValueError)

tensor([[[1, 2],
         [2, 3]],

        [[4, 5],
         [7, 9]]])
torch.Size([2, 2, 2])
torch.int64
tensor([[[1., 2.],
         [2., 3.]],

        [[4., 5.],
         [7., 9.]]])
torch.Size([2, 2, 2])
torch.float32
expected sequence of length 3 at dim 2 (got 2)
<class 'ValueError'>


# Tensor operations and gradients

We can combine tensor with usual arithmetic operations available at python.

In [6]:
# Creating tensors.
x= torch.tensor(2.)
w= torch.tensor(3.,requires_grad=True)
b= torch.tensor(4.,requires_grad=True)

Arithmetic operation

Combining Tensors to create new one.

In [7]:
y=w*x+b
y

tensor(10., grad_fn=<AddBackward0>)

In pytorch, we can automatically compute the derivative of y w.r.t. the tensors that have `require_grads` set to True(w,b). To compute derivatives, call 
`.backward `
on result i.e. y. 
The results are stored in .grad property.

# Computing Derivatives

Gradients: With metrics

Derivatives: With numbers

In [8]:
y.backward()# works only on differentiable function, any complex function, uses calculus(not numerical methods generally)
print('dy/dx',x.grad)
print('dy/dw',w.grad)
print('dy/db',b.grad)

dy/dx None
dy/dw tensor(2.)
dy/db tensor(1.)


### For matrices

In [13]:
# Creating tensors.
x= torch.tensor([[1.,2],[2.,3],[4,5],[7,9]])
w= torch.tensor([[1.,2],[2.,3],[4,5],[10,9]],requires_grad=True)
b= torch.tensor([[10,2],[2.,3],[4,5],[7,9]],requires_grad=True)
y=w*x+b
print(y)
external_grad = torch.tensor([[1.,1.],[1.,1.],[1.,1.],[1.,1.]])
y.backward(gradient=external_grad)
print('dy/dx',x.grad)
print('dy/dw',w.grad)
print('dy/db',b.grad)

tensor([[11.,  6.],
        [ 6., 12.],
        [20., 30.],
        [77., 90.]], grad_fn=<AddBackward0>)
dy/dx None
dy/dw tensor([[1., 2.],
        [2., 3.],
        [4., 5.],
        [7., 9.]])
dy/db tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])


# Interoperability with numpy

Numpy: 

*   Enables operations on large multidimensional arrays.
*   Used for multiplication and scientific computings.
*   Efficient because implemented in C++.
*   Has large ecosystem of supporting libraries.
*   Instead of reinventing the wheel(creating pre existing things), python interoperates really well numpy to levarage its existing ecosystem of tools and libraries.
*   Interoperability is important because most of the most datasets are read and preprocessed as numpy arrays.
*   Sometimes for deployment and web applications also, we have to convert to numpy arrays.

# Creating numpy array and converting it to pytorch tensor and vice versa.

## Some facts:
* Arrays have arbitrary shapes whereas tensors have regular shape.
* array and torch tensors exhibits same properties.
* Pytorch is specifically desinged to work on GPUs.
* To run any code on NVIDIA GPU, the code should be written in CUDA. It

 is a programming language like a flavour of C.


Both have same datatypes.

In [9]:
p=np.array([[1,2],[3.,4]])#numpy method
q=torch.from_numpy(p)#torch method, thin wrpper from python to perform operation efficiently on GPU.
r=q.numpy()#method of a tensor
print(p)
print(q)
print(r)
print(p.dtype)
print(q.dtype)
print(r.dtype)

[[1. 2.]
 [3. 4.]]
tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)
[[1. 2.]
 [3. 4.]]
float64
torch.float64
float64


# Jovian Material

## Interoperability with Numpy

[Numpy](http://www.numpy.org/) is a popular open-source library used for mathematical and scientific computing in Python. It enables efficient operations on large multi-dimensional arrays and has a vast ecosystem of supporting libraries, including:

* [Pandas](https://pandas.pydata.org/) for file I/O and data analysis
* [Matplotlib](https://matplotlib.org/) for plotting and visualization
* [OpenCV](https://opencv.org/) for image and video processing


If you're interested in learning more about Numpy and other data science libraries in Python, check out this tutorial series: https://jovian.ai/aakashns/python-numerical-computing-with-numpy .

Instead of reinventing the wheel, PyTorch interoperates well with Numpy to leverage its existing ecosystem of tools and libraries.

The interoperability between PyTorch and Numpy is essential because most datasets you'll work with will likely be read and preprocessed as Numpy arrays.

You might wonder why we need a library like PyTorch at all since Numpy already provides data structures and utilities for working with multi-dimensional numeric data. There are two main reasons:

1. **Autograd**: The ability to automatically compute gradients for tensor operations is essential for training deep learning models.
2. **GPU support**: While working with massive datasets and large models, PyTorch tensor operations can be performed efficiently using a Graphics Processing Unit (GPU). Computations that might typically take hours can be completed within minutes using GPUs.

We'll leverage both these features of PyTorch extensively in this tutorial series.

## Summary and Further Reading

Try out this assignment to learn more about tensor operations in PyTorch: https://jovian.ai/aakashns/01-tensor-operations


This tutorial covers the following topics:

* Introductions to PyTorch tensors
* Tensor operations and gradients
* Interoperability between PyTorch and Numpy


You can learn more about PyTorch tensors here: https://pytorch.org/docs/stable/tensors.html. 


The material in this series is inspired by:

* [PyTorch Tutorial for Deep Learning Researchers](https://github.com/yunjey/pytorch-tutorial) by Yunjey Choi 
* [FastAI development notebooks](https://github.com/fastai/fastai_docs/tree/master/dev_nb) by Jeremy Howard. 

With this, we complete our discussion of tensors and gradients in PyTorch, and we're ready to move on to the next topic: [Gradient Descent & Linear Regression](https://jovian.ai/aakashns/02-linear-regression).

## Questions for Review

Try answering the following questions to test your understanding of the topics covered in this notebook:

1. What is PyTorch?
2. What is a Jupyter notebook?
3. What is Google Colab?
4. How do you install PyTorch?
5. How do you import the `torch` module?
6. What is a vector? Give an example.
7. What is a matrix? Give an example.
8. What is a tensor?
9. How do you create a PyTorch tensor? Illustrate with examples.
10. What is the difference between a tensor and a vector or a matrix?
11. Is every tensor a matrix?
12. Is every matrix a tensor?
13. What does the `dtype` property of a tensor represent?
14. Is it possible to create a tensor with elements of different data types?
15. How do you inspect the number of dimensions of a tensor and the length along each dimension?
16. Is it possible to create a tensor with the values `[[1, 2, 3], [4, 5]]`? Why or why not?
17. How do you perform arithmetic operations on tensors? Illustrate with examples?
18. What happens if you specify `requires_grad=True` while creating a tensor? Illustrate with an example.
19. What is autograd in PyTorch? How is it useful?
20. What happens when you invoke  the `backward` method of a tensor?
21. How do you check the derivates of a result tensor w.r.t. the tensors used to compute its value?
22. Give some examples of functions available in the `torch` module for creating tensors.
23. Give some examples of functions available in the `torch` module for performing mathematical operations on tensors.
24. Where can you find the list of tensor operations available in PyTorch?
25. What is Numpy?
26. How do you create a Numpy array?
27. How do you create a PyTorch tensor using a Numpy array?
28. How do you create a Numpy array using a PyTorch tensor?
29. Why is interoperability between PyTorch and Numpy important?
30. What is the purpose of a library like PyTorch if Numpy already provides data structures and utilities to with multi-dimensional numeric data?
31. What is Jovian?
32. How do you upload your notebooks to Jovian using `jovian.commit` ?