<a href="https://colab.research.google.com/github/philsaurabh/Pytorch-zero-to-GANs-Jovian/blob/main/Pytorch_Zero_to_GANs_Linear_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Introduction to Linear Regression

In this tutorial, we'll discuss one of the foundational algorithms in machine learning: *Linear regression*. We'll create a model that predicts crop yields for apples and oranges (*target variables*) by looking at the average temperature, rainfall, and humidity (*input variables or features*) in a region. Here's the training data:

![linear-regression-training-data](https://i.imgur.com/6Ujttb4.png)

In a linear regression model, each target variable is estimated to be a weighted sum of the input variables, offset by some constant, known as a bias :

```
yield_apple  = w11 * temp + w12 * rainfall + w13 * humidity + b1
yield_orange = w21 * temp + w22 * rainfall + w23 * humidity + b2
```

Visually, it means that the yield of apples is a linear or planar function of temperature, rainfall and humidity:

![linear-regression-graph](https://i.imgur.com/4DJ9f8X.png)

# Importing Libraries

In [22]:
import torch
import numpy as np

# Training Data
Can be represented usin two metrices :
1. inputs
2. targets
each with one row per observation and one column per variable.

In [23]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')


In [24]:
# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')
print(targets.dtype)

float32


We've separated the input and target variables because we'll operate on them separately. Also, we've created numpy arrays, because this is typically how you would work with training data: read some CSV files as numpy arrays, do some processing, and then convert them to PyTorch tensors.

# Tensor conversion

In [25]:
# Convert inputs and targets to tensors
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)
print(inputs.dtype)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])
torch.float32


## Linear regression model from scratch

The weights and biases (`w11, w12,... w23, b1 & b2`) can also be represented as matrices, initialized as random values. The first row of `w` and the first element of `b` are used to predict the first target variable, i.e., yield of apples, and similarly, the second for oranges.

In [26]:
# Weights and biases
w = torch.randn(2, 3, requires_grad=True)
b = torch.randn(2, requires_grad=True)
print(w)
print(b)

tensor([[-1.9791, -2.4543,  1.0714],
        [-1.8844, -1.1589,  0.1230]], requires_grad=True)
tensor([ 2.6122, -0.6012], requires_grad=True)


`torch.randn` creates a tensor with the given shape, with elements picked randomly from a [normal distribution](https://en.wikipedia.org/wiki/Normal_distribution) with mean 0 and standard deviation 1. So, the values enerated will be in the range(-1,1).

Our *model* is simply a function that performs a matrix multiplication of the `inputs` and the weights `w` (transposed for the dimension lineup) and adds the bias `b` (replicated for each observation).

![matrix-mult](https://i.imgur.com/WGXLFvA.png)

We want to predict the target values, but it will predict some different values due to random initial weights.

We can define the model as follows:

In [27]:
def model(x):
    return x @ w.t() + b

`@` represents matrix multiplication in PyTorch, and the `.t` method returns the transpose of a tensor.

The matrix obtained by passing the input data into the model is a set of predictions for the target variables.

In [28]:
# Generate predictions
preds = model(inputs)
print(preds)

tensor([[-260.2300, -210.5222],
        [-324.8945, -266.1959],
        [-436.3055, -312.7047],
        [-265.1487, -238.0958],
        [-294.5604, -233.2712]], grad_fn=<AddBackward0>)


# Comparing with targets

In [29]:
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


You can see a big difference between our model's predictions and the actual targets because we've initialized our model with random weights and biases. Obviously, we can't expect a randomly initialized model to *just work*.

## Loss function

Before we improve our model, we need a way to evaluate how well our model is performing. We can compare the model's predictions with the actual targets using the following method:

* Calculate the difference between the two matrices (`preds` and `targets`).
* Square all elements of the difference matrix to remove negative values.
* Calculate the average of the elements in the resulting matrix.

The result is a single number, known as the **mean squared error** (MSE).

In [30]:
# MSE loss
def mse(t1, t2):
    diff = t1 - t2
    return torch.sum(diff * diff) / diff.numel()

`torch.sum` returns the sum of all the elements in a tensor. The `.numel` method of a tensor returns the number of elements in a tensor. Let's compute the mean squared error for the current predictions of our model.

In [31]:
# Compute loss
loss = mse(preds, targets)
print(loss)

tensor(142557.5469, grad_fn=<DivBackward0>)


Here’s how we can interpret the result: *On average, each element in the prediction differs from the actual target by the square root of the loss*. And that’s pretty bad, considering the numbers we are trying to predict are themselves in the range 50–200. The result is called the *loss* because it indicates how bad the model is at predicting the target variables. It represents information loss in the model: the lower the loss, the better the model.

## Compute gradients

With PyTorch, we can automatically compute the gradient or derivative of the loss w.r.t. to the weights and biases because they have `requires_grad` set to `True`. We'll see how this is useful in just a moment.

In [32]:
# Compute gradients
loss.backward()

The gradients are stored in the `.grad` property of the respective tensors. Note that the derivative of the loss w.r.t. the weights matrix is itself a matrix with the same dimensions.

In [33]:
# Gradients for weights
print(w)
print(w.grad)

tensor([[-1.9791, -2.4543,  1.0714],
        [-1.8844, -1.1589,  0.1230]], requires_grad=True)
tensor([[-33010.7227, -36366.0547, -22047.3203],
        [-29007.1484, -31295.9609, -19250.2793]])


In [34]:
print(b)
print(b.grad)

tensor([ 2.6122, -0.6012], requires_grad=True)
tensor([-392.4279, -344.1580])


## Adjust weights and biases to reduce the loss

The loss is a [quadratic function](https://en.wikipedia.org/wiki/Quadratic_function) of our weights and biases, and our objective is to find the set of weights where the loss is the lowest. If we plot a graph of the loss w.r.t any individual weight or bias element, it will look like the figure shown below. An important insight from calculus is that the gradient indicates the rate of change of the loss, i.e., the loss function's [slope](https://en.wikipedia.org/wiki/Slope) w.r.t. the weights and biases.

If a gradient element is **positive**:

* **increasing** the weight element's value slightly will **increase** the loss
* **decreasing** the weight element's value slightly will **decrease** the loss

![postive-gradient](https://i.imgur.com/WLzJ4xP.png)

If a gradient element is **negative**:

* **increasing** the weight element's value slightly will **decrease** the loss
* **decreasing** the weight element's value slightly will **increase** the loss

![negative=gradient](https://i.imgur.com/dvG2fxU.png)

The increase or decrease in the loss by changing a weight element is proportional to the gradient of the loss w.r.t. that element. This observation forms the basis of _the gradient descent_ optimization algorithm that we'll use to improve our model (by _descending_ along the _gradient_).

We can subtract from each weight element a small quantity proportional to the derivative of the loss w.r.t. that element to reduce the loss slightly.

In [35]:
w
w.grad

tensor([[-33010.7227, -36366.0547, -22047.3203],
        [-29007.1484, -31295.9609, -19250.2793]])

In [36]:
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5

We multiply the gradients with a very small number (`10^-5` in this case) to ensure that we don't modify the weights by a very large amount. We want to take a small step in the downhill direction of the gradient, not a giant leap. This number is called the *learning rate* of the algorithm. 

We use `torch.no_grad` to indicate to PyTorch that we shouldn't track, calculate, or modify gradients while updating the weights and biases.

In [37]:
print(w)
print(b)

tensor([[-1.6490, -2.0907,  1.2919],
        [-1.5944, -0.8459,  0.3155]], requires_grad=True)
tensor([ 2.6161, -0.5978], requires_grad=True)


In [38]:
# Let's verify that the loss is actually lower
preds=model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(96215.3516, grad_fn=<DivBackward0>)


Before we proceed, we reset the gradients to zero by invoking the `.zero_()` method. We need to do this because PyTorch accumulates gradients. Otherwise, the next time we invoke `.backward` on the loss, the new gradient values are added to the existing gradients, which may lead to unexpected results.

In [39]:
w.grad.zero_()
b.grad.zero_()
print(w.grad)
print(b.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0.])


## Train the model using gradient descent

As seen above, we reduce the loss and improve our model using the gradient descent optimization algorithm. Thus, we can _train_ the model using the following steps:

1. Generate predictions

2. Calculate the loss

3. Compute gradients w.r.t the weights and biases

4. Adjust the weights by subtracting a small quantity proportional to the gradient

5. Reset the gradients to zero

Let's implement the above step by step.

In [42]:
# Generate predictions
preds = model(inputs)
print(preds)

tensor([[-202.2827, -160.0976],
        [-248.7384, -199.9353],
        [-346.0643, -234.3633],
        [-207.6790, -187.9252],
        [-221.4345, -169.7336]], grad_fn=<AddBackward0>)


In [43]:
# Calculate the loss
loss = mse(preds, targets)
print(loss)

tensor(96215.3516, grad_fn=<DivBackward0>)


In [44]:
# Compute gradients
loss.backward()
print(w.grad)
print(b.grad)

tensor([[-27026.9316, -29932.4883, -18078.3359],
        [-23801.5664, -25703.1445, -15798.9414]])
tensor([-321.4398, -282.4110])


In [45]:
# Adjust weights & reset gradients
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

In [46]:
print(w)
print(b)

tensor([[-1.3787, -1.7913,  1.4727],
        [-1.3564, -0.5889,  0.4735]], requires_grad=True)
tensor([ 2.6193, -0.5949], requires_grad=True)


In [47]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(64984.7383, grad_fn=<DivBackward0>)


We have already achieved a significant reduction in the loss merely by adjusting the weights and biases slightly using gradient descent.

## Train for multiple epochs

To reduce the loss further, we can repeat the process of adjusting the weights and biases using the gradients multiple times. Each iteration is called an _epoch_. Let's train the model for 100 epochs.

In [55]:
lr=1e-5
# Train for 100 epochs
for i in range(100):
    preds = model(inputs)
    loss = mse(preds, targets)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * lr
        b -= b.grad * lr
        w.grad.zero_()
        b.grad.zero_()

Once again, let's verify that the loss is now lower:

In [56]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(104.0998, grad_fn=<DivBackward0>)


The loss is now much lower than its initial value. Let's look at the model's predictions and compare them with the targets.

In [57]:
# Predictions
preds

tensor([[ 57.5515,  70.1764],
        [ 92.4889, 102.5352],
        [ 94.6958, 128.9282],
        [ 21.7820,  37.0082],
        [119.9170, 122.2716]], grad_fn=<AddBackward0>)

In [58]:
# Targets
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

The predictions are now quite close to the target variables. We can get even better results by training for a few more epochs. 

# Linear regression using PyTorch built-ins

We've implemented linear regression & gradient descent model using some basic tensor operations. However, since this is a common pattern in deep learning, PyTorch provides several built-in functions and classes to make it easy to create and train models with just a few lines of code.

Let's begin by importing the `torch.nn` package from PyTorch, which contains utility classes for building neural networks.

In [59]:
import torch.nn as nn

As before, we represent the inputs and targets and matrices.

In [60]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70], 
                   [74, 66, 43], 
                   [91, 87, 65], 
                   [88, 134, 59], 
                   [101, 44, 37], 
                   [68, 96, 71], 
                   [73, 66, 44], 
                   [92, 87, 64], 
                   [87, 135, 57], 
                   [103, 43, 36], 
                   [68, 97, 70]], 
                  dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119],
                    [57, 69], 
                    [80, 102], 
                    [118, 132], 
                    [21, 38], 
                    [104, 118], 
                    [57, 69], 
                    [82, 100], 
                    [118, 134], 
                    [20, 38], 
                    [102, 120]], 
                   dtype='float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [62]:
print(inputs)
inputs.dtype

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 74.,  66.,  43.],
        [ 91.,  87.,  65.],
        [ 88., 134.,  59.],
        [101.,  44.,  37.],
        [ 68.,  96.,  71.],
        [ 73.,  66.,  44.],
        [ 92.,  87.,  64.],
        [ 87., 135.,  57.],
        [103.,  43.,  36.],
        [ 68.,  97.,  70.]])


torch.float32

We are using 15 training examples to illustrate how to work with large datasets in small batches. 

## Dataset and DataLoader

We'll create a `TensorDataset`, which allows access to rows from `inputs` and `targets` as tuples, and provides standard APIs for working with many different types of datasets in PyTorch.

In [63]:
from torch.utils.data import TensorDataset

In [64]:
# Define dataset
train_ds = TensorDataset(inputs, targets)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]), tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [65]:
train_ds[[1,3,7,5]]

(tensor([[ 91.,  88.,  64.],
         [102.,  43.,  37.],
         [ 88., 134.,  59.],
         [ 74.,  66.,  43.]]), tensor([[ 81., 101.],
         [ 22.,  37.],
         [118., 132.],
         [ 57.,  69.]]))

The `TensorDataset` allows us to access a small section of the training data using the array indexing notation (`[0:3]` in the above code). It returns a tuple with two elements. The first element contains the input variables for the selected rows, and the second contains the targets.

We'll also create a `DataLoader`, which can split the data into batches of a predefined size while training. It also provides other utilities like shuffling and random sampling of the data.

In [66]:
from torch.utils.data import DataLoader

In [67]:
# Define data loader
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle=True)

We can use the data loader in a `for` loop. Let's look at an example.

In [68]:
for xb, yb in train_dl:
    print(xb)
    print(yb)
    break

tensor([[ 74.,  66.,  43.],
        [ 88., 134.,  59.],
        [ 91.,  87.,  65.],
        [ 91.,  88.,  64.],
        [ 69.,  96.,  70.]])
tensor([[ 57.,  69.],
        [118., 132.],
        [ 80., 102.],
        [ 81., 101.],
        [103., 119.]])


In [69]:
for xb, yb in train_dl:
    print('Batch===========')
    print(xb)
    print(yb)
    #break

Batch===========
tensor([[ 73.,  66.,  44.],
        [101.,  44.,  37.],
        [102.,  43.,  37.],
        [ 87., 135.,  57.],
        [ 73.,  67.,  43.]])
tensor([[ 57.,  69.],
        [ 21.,  38.],
        [ 22.,  37.],
        [118., 134.],
        [ 56.,  70.]])
Batch===========
tensor([[ 87., 134.,  58.],
        [103.,  43.,  36.],
        [ 91.,  88.,  64.],
        [ 74.,  66.,  43.],
        [ 92.,  87.,  64.]])
tensor([[119., 133.],
        [ 20.,  38.],
        [ 81., 101.],
        [ 57.,  69.],
        [ 82., 100.]])
Batch===========
tensor([[ 91.,  87.,  65.],
        [ 88., 134.,  59.],
        [ 68.,  97.,  70.],
        [ 69.,  96.,  70.],
        [ 68.,  96.,  71.]])
tensor([[ 80., 102.],
        [118., 132.],
        [102., 120.],
        [103., 119.],
        [104., 118.]])


In each iteration, the data loader returns one batch of data with the given batch size. If `shuffle` is set to `True`, it shuffles the training data before creating batches. Shuffling helps randomize the input to the optimization algorithm, leading to a faster reduction in the loss.

## nn.Linear

Instead of initializing the weights & biases manually, we can define the model using the `nn.Linear` class from PyTorch, which does it automatically.

In [70]:
# Define model
model = nn.Linear(3, 2)# 3 inputs and 2 outputs
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[-0.0967,  0.1570,  0.2209],
        [ 0.2299,  0.4518,  0.2383]], requires_grad=True)
Parameter containing:
tensor([ 0.1929, -0.5063], requires_grad=True)


PyTorch models also have a helpful `.parameters` method, which returns a list containing all the weights and bias matrices present in the model. For our linear regression model, we have one weight matrix and one bias matrix.

In [71]:
# Parameters
list(model.parameters())

[Parameter containing:
 tensor([[-0.0967,  0.1570,  0.2209],
         [ 0.2299,  0.4518,  0.2383]], requires_grad=True),
 Parameter containing:
 tensor([ 0.1929, -0.5063], requires_grad=True)]

We can use the model to generate predictions in the same way as before.

In [72]:
# Generate predictions
preds = model(inputs)
preds

tensor([[13.1522, 56.7912],
        [19.3474, 75.4208],
        [25.6333, 93.8546],
        [ 5.2533, 51.1842],
        [24.0566, 75.4079],
        [12.8984, 56.5693],
        [19.4112, 75.2072],
        [25.7574, 94.3227],
        [ 5.5070, 51.4062],
        [24.3741, 75.4163],
        [13.2160, 56.5777],
        [19.0936, 75.1988],
        [25.5695, 94.0681],
        [ 4.9357, 51.1758],
        [24.3103, 75.6299]], grad_fn=<AddmmBackward>)

## Loss Function

Instead of defining a loss function manually, we can use the built-in loss function `mse_loss`.

In [73]:
# Import nn.functional
import torch.nn.functional as F

The `nn.functional` package contains many useful loss functions and several other utilities. 

In [74]:
# Define loss function
loss_fn = F.mse_loss

# Documentation Function

In [76]:
?nn.Linear

Let's compute the loss for the current predictions of our model.

In [77]:
loss = loss_fn(model(inputs), targets)
print(loss)

tensor(2516.8665, grad_fn=<MseLossBackward>)


## Optimizer

Instead of manually manipulating the model's weights & biases using gradients, we can use the optimizer `optim.SGD`. SGD is short for "stochastic gradient descent". The term _stochastic_ indicates that samples are selected in random batches instead of as a single group.

In [79]:
# Define optimizer
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

## Train the model

We are now ready to train the model. We'll follow the same process to implement gradient descent:

1. Generate predictions

2. Calculate the loss

3. Compute gradients w.r.t the weights and biases

4. Adjust the weights by subtracting a small quantity proportional to the gradient

5. Reset the gradients to zero

The only change is that we'll work batches of data instead of processing the entire training data in every iteration. Let's define a utility function `fit` that trains the model for a given number of epochs.

In [80]:
# Utility function to train the model
def fit(num_epochs, model, loss_fn, opt, train_dl):
    
    # Repeat for given number of epochs
    for epoch in range(num_epochs):
        
        # Train with batches of data
        for xb,yb in train_dl:
            
            # 1. Generate predictions
            pred = model(xb)
            
            # 2. Calculate loss
            loss = loss_fn(pred, yb)
            
            # 3. Compute gradients
            loss.backward()
            
            # 4. Update parameters using gradients
            opt.step()
            
            # 5. Reset the gradients to zero
            opt.zero_grad()
        
        # Print the progress
        if (epoch+1) % 10 == 0:
            print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))

Some things to note above:

* We use the data loader defined earlier to get batches of data for every iteration.

* Instead of updating parameters (weights and biases) manually, we use `opt.step` to perform the update and `opt.zero_grad` to reset the gradients to zero.

* We've also added a log statement that prints the loss from the last batch of data for every 10th epoch to track training progress. `loss.item` returns the actual value stored in the loss tensor.

Let's train the model for 100 epochs.

In [81]:
fit(100, model, loss_fn, opt, train_dl)

Epoch [10/100], Loss: 187.2721
Epoch [20/100], Loss: 250.6567
Epoch [30/100], Loss: 42.0722
Epoch [40/100], Loss: 85.1830
Epoch [50/100], Loss: 96.9162
Epoch [60/100], Loss: 22.1456
Epoch [70/100], Loss: 48.1754
Epoch [80/100], Loss: 27.0303
Epoch [90/100], Loss: 15.0102
Epoch [100/100], Loss: 8.7970


Let's generate predictions using our model and verify that they're close to our targets.

In [82]:
# Generate predictions
preds = model(inputs)
preds

tensor([[ 57.9205,  71.3801],
        [ 81.3309,  98.2110],
        [118.1342, 136.4583],
        [ 26.2064,  43.7067],
        [ 97.5406, 110.8815],
        [ 56.7891,  70.3754],
        [ 81.0076,  97.8197],
        [118.3650, 136.8333],
        [ 27.3378,  44.7114],
        [ 98.3488, 111.4949],
        [ 57.5973,  70.9887],
        [ 80.1995,  97.2063],
        [118.4574, 136.8496],
        [ 25.3982,  43.0934],
        [ 98.6720, 111.8862]], grad_fn=<AddmmBackward>)

In [83]:
# Compare with targets
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])

Indeed, the predictions are quite close to our targets. We have a trained a reasonably good model to predict crop yields for apples and oranges by looking at the average temperature, rainfall, and humidity in a region. We can use it to make predictions of crop yields for new regions by passing a batch containing a single row of input.

In [84]:
model(torch.tensor([[75, 63, 44.]]))

tensor([[54.4917, 68.0938]], grad_fn=<AddmmBackward>)

## Machine Learning vs. Classical Programming

The approach we've taken in this tutorial is very different from programming as you might know it. Usually, we write programs that take some inputs, perform some operations, and return a result. 

However, in this notebook, we've defined a "model" that assumes a specific relationship between the inputs and the outputs, expressed using some unknown parameters (weights & biases). We then show the model some know inputs and outputs and _train_ the model to come up with good values for the unknown parameters. Once trained, the model can be used to compute the outputs for new inputs.

This paradigm of programming is known as _machine learning_, where we use data to figure out the relationship between inputs and outputs. _Deep learning_ is a branch of machine learning that uses matrix operations, non-linear activation functions and gradient descent to build and train models. Andrej Karpathy, the director of AI at Tesla Motors, has written a great blog post on this topics, titled [Software 2.0](https://medium.com/@karpathy/software-2-0-a64152b37c35).

This picture from book [Deep Learning with Python](https://www.manning.com/books/deep-learning-with-python) by Francois Chollet captures the difference between classical programming and machine learning:

![](https://i.imgur.com/oJEQe7k.png)

Keep this picture in mind as you work through the next few tutorials. 


## Exercises and Further Reading

We've covered the following topics in this tutorial:

- Introduction to linear regression and gradient descent
- Implementing a linear regression model using PyTorch tensors
- Training a linear regression model using the gradient descent algorithm
- Implementing gradient descent and linear regression using PyTorch built-in


Here are some resources for learning more about linear regression and gradient descent:

* An visual & animated explanation of gradient descent: https://www.youtube.com/watch?v=IHZwWFHWa-w

* For a more detailed explanation of derivates and gradient descent, see [these notes from a Udacity course](https://storage.googleapis.com/supplemental_media/udacityu/315142919/Gradient%20Descent.pdf). 

* For an animated visualization of how linear regression works, [see this post](https://hackernoon.com/visualizing-linear-regression-with-pytorch-9261f49edb09).

* For a more mathematical treatment of matrix calculus, linear regression and gradient descent, you should check out [Andrew Ng's excellent course notes](https://github.com/Cleo-Stanford-CS/CS229_Notes/blob/master/lectures/cs229-notes1.pdf) from CS229 at Stanford University.

* To practice and test your skills, you can participate in the [Boston Housing Price Prediction](https://www.kaggle.com/c/boston-housing) competition on Kaggle, a website that hosts data science competitions.

With this, we complete our discussion of linear regression in PyTorch, and we’re ready to move on to the next topic: [Working with Images & Logistic Regression](https://jovian.ai/aakashns/03-logistic-regression).